"""Evaluate PROMPT_V5 on the 300-row Validation Set with KaggleTaskLM."""

import sys
from pathlib import Path
import json
import math
import time
import pandas as pd

import dspy
from sklearn.metrics import f1_score

ROOT_DIR = Path(__file__).resolve().parents[3]
if str(ROOT_DIR) not in sys.path:
    sys.path.insert(0, str(ROOT_DIR))

from client.nvidia_client import _client, chat_completion, STUDENT_MODEL as MODEL
from src.track_one.utils.evaluate import _seed_probabilities, _final_answer_label, _calculate_full_metrics

from src.track_one.optimization.run_gepa_optimization import load_stratified_splits

TEMPERATURE = 0.0
TOP_P = 1.0
MAX_TOKENS = 65_536
REASONING_EFFORT = "medium"
TOP_LOGPROBS = 20

class KaggleTaskLM(dspy.LM):
    def __init__(self, seed: int, temperature: float = 0.0):
        super().__init__("openai/gpt-oss-120b")
        self.seed = seed
        self.temperature = temperature
        self.client = _client()
        
    def __call__(self, prompt=None, messages=None, **kwargs):
        if messages:
            # Preserve the exact System and User roles generated by DSPy
            api_messages = messages
        else:
            api_messages = [{"role": "user", "content": prompt}]
            
        request = {
            "model": MODEL,
            "messages": api_messages,
            "temperature": self.temperature,
            "top_p": TOP_P,
            "seed": self.seed,
            "max_tokens": MAX_TOKENS,
            "logprobs": True,
            "top_logprobs": TOP_LOGPROBS,
            "extra_body": {"reasoning": {"effort": REASONING_EFFORT}},
        }
        response = chat_completion(self.client, request)
        text = response.get("choices", [{}])[0].get("message", {}).get("content", "")
        self.history.append({
            "prompt": prompt, 
            "messages": messages,
            "api_messages": api_messages,
            "response": text, 
            "kwargs": kwargs, 
            "raw_response": response
        })
        return [text], response



def main():
    print("Loading test dataset...", flush=True)
    test_df = pd.read_csv("data/test.csv")
    print(f"Loaded {len(test_df)} target genes from test.csv.", flush=True)

    with open("src/track_one/output/system_prompt.txt", "r") as f:
        system_prompt = f.read()
    with open("src/track_one/output/user_prompt.txt", "r") as f:
        user_prompt = f.read()

    out_path = Path("outputs/track_a/default/submission.csv")
    out_path.parent.mkdir(parents=True, exist_ok=True)
    
    # Safe Resume logic
    processed_ids = set()
    if out_path.exists():
        existing_df = pd.read_csv(out_path)
        processed_ids = set(existing_df['id'])
        print(f"Safe Resume: Found existing submission.csv with {len(processed_ids)} rows.", flush=True)
    else:
        # Write header
        import csv
        with open(out_path, 'w', newline='') as f:
            writer = csv.writer(f)
            writer.writerow([
                "id", "prediction_up", "prediction_down", 
                "prediction_up_seed42", "prediction_down_seed42", 
                "prediction_up_seed43", "prediction_down_seed43", 
                "prediction_up_seed44", "prediction_down_seed44", 
                "reasoning_trace_seed42", "reasoning_trace_seed43", "reasoning_trace_seed44", 
                "tokens_used", "prompt_tokens", "model_name"
            ])
            
    # Filter the dataframe
    remaining_df = test_df[~test_df['id'].isin(processed_ids)]
    
    print(f"Processing {len(remaining_df)} remaining rows.", flush=True)
    
    if len(remaining_df) == 0:
        print("All rows processed successfully!")
        return

    from concurrent.futures import ThreadPoolExecutor, as_completed
    import csv
    
    def process_row(row_idx, row):
        try:
            import re
            user_msg = user_prompt.format(pert=row['pert'], gene=row['gene'])
            messages = [
                {"role": "system", "content": system_prompt},
                {"role": "user", "content": user_msg}
            ]
            
            seed_data = {}
            total_completion_tokens = 0
            total_prompt_tokens = 0
            
            for seed in (42, 43, 44):
                try:
                    lm_instance = KaggleTaskLM(seed=seed, temperature=0.7)
                    response_texts, data = lm_instance(messages=messages)
                    text = response_texts[0]
                    
                    # Extract reasoning trace for THIS seed
                    parsed_reasoning = ""
                    r_match = re.search(r"\[\[ ## reasoning ## \]\](.*?)\[\[ ## label ## \]\]", text, re.DOTALL)
                    if r_match:
                        parsed_reasoning = r_match.group(1).strip()
                        
                    # Extract probabilities for THIS seed
                    probs = _seed_probabilities(data)
                    
                    # Track Tokens
                    usage = data.get("usage", {})
                    total_completion_tokens += usage.get("completion_tokens", 0)
                    if seed == 42:
                        total_prompt_tokens = usage.get("prompt_tokens", 0) # Prompt tokens are same across seeds
                        
                    seed_data[seed] = {
                        "probs": probs if probs else {"up": 0.333, "down": 0.333, "none": 0.334},
                        "reasoning": parsed_reasoning
                    }
                except Exception as e:
                    print(f"Warning: Seed {seed} failed for {row['pert']}_{row['gene']}: {e}", flush=True)
                    seed_data[seed] = {"probs": {"up": 0.333, "down": 0.333, "none": 0.334}, "reasoning": "Error"}

            # Averaging
            avg_up = sum(seed_data[s]["probs"]["up"] for s in (42, 43, 44)) / 3
            avg_down = sum(seed_data[s]["probs"]["down"] for s in (42, 43, 44)) / 3
            
            result_row = {
                "id": row['id'],
                "prediction_up": avg_up,
                "prediction_down": avg_down,
                "prediction_up_seed42": seed_data[42]["probs"]["up"],
                "prediction_down_seed42": seed_data[42]["probs"]["down"],
                "prediction_up_seed43": seed_data[43]["probs"]["up"],
                "prediction_down_seed43": seed_data[43]["probs"]["down"],
                "prediction_up_seed44": seed_data[44]["probs"]["up"],
                "prediction_down_seed44": seed_data[44]["probs"]["down"],
                "reasoning_trace_seed42": seed_data[42]["reasoning"],
                "reasoning_trace_seed43": seed_data[43]["reasoning"],
                "reasoning_trace_seed44": seed_data[44]["reasoning"],
                "tokens_used": total_completion_tokens,
                "prompt_tokens": total_prompt_tokens,
                "model_name": "gpt-oss-120b"
            }
            return row_idx, row, result_row, None
        except Exception as e:
            return row_idx, row, None, e
            
    # Write lock for thread-safe writing to CSV
    import threading
    csv_lock = threading.Lock()
    
    with ThreadPoolExecutor(max_workers=2) as executor:
        futures = {executor.submit(process_row, idx, row): row for idx, row in remaining_df.iterrows()}
        
        completed_count = 0
        for future in as_completed(futures):
            idx, row, result_row, err = future.result()
            if err:
                print(f"Error on {row['pert']}_{row['gene']}: {err}", flush=True)
                continue
                
            # Safely append to CSV in real-time
            with csv_lock:
                with open(out_path, 'a', newline='') as f:
                    writer = csv.DictWriter(f, fieldnames=[
                        "id", "prediction_up", "prediction_down", 
                        "prediction_up_seed42", "prediction_down_seed42", 
                        "prediction_up_seed43", "prediction_down_seed43", 
                        "prediction_up_seed44", "prediction_down_seed44", 
                        "reasoning_trace_seed42", "reasoning_trace_seed43", "reasoning_trace_seed44", 
                        "tokens_used", "prompt_tokens", "model_name"
                    ])
                    writer.writerow(result_row)
                    
            completed_count += 1
            print(f"[{completed_count}/{len(remaining_df)}] Written {row['id']} to disk. Up: {result_row['prediction_up']}, Down: {result_row['prediction_down']}", flush=True)

if __name__ == "__main__":
    main()
